/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignSystemOrganizationRouteImport } from './routes/design-system.organization'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTenantManagementRouteImport } from './routes/_app.tenant-management'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppRecruitmentRequisitionsRouteImport } from './routes/_app.recruitment-requisitions'
import { Route as AppRecruitmentPreboardingRouteImport } from './routes/_app.recruitment-preboarding'
import { Route as AppRecruitmentPositionsRouteImport } from './routes/_app.recruitment-positions'
import { Route as AppRecruitmentPipelineRouteImport } from './routes/_app.recruitment-pipeline'
import { Route as AppRecruitmentOffersRouteImport } from './routes/_app.recruitment-offers'
import { Route as AppRecruitmentInterviewsRouteImport } from './routes/_app.recruitment-interviews'
import { Route as AppRecruitmentCandidatesRouteImport } from './routes/_app.recruitment-candidates'
import { Route as AppRecruitmentRouteImport } from './routes/_app.recruitment'
import { Route as AppProviderDashboardRouteImport } from './routes/_app.provider-dashboard'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPayslipsRouteImport } from './routes/_app.payslips'
import { Route as AppOutsourcingRouteImport } from './routes/_app.outsourcing'
import { Route as AppOrganizationRouteImport } from './routes/_app.organization'
import { Route as AppOperationsDashboardRouteImport } from './routes/_app.operations-dashboard'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMyTeamRouteImport } from './routes/_app.my-team'
import { Route as AppMyPayslipsRouteImport } from './routes/_app.my-payslips'
import { Route as AppMyLeaveRouteImport } from './routes/_app.my-leave'
import { Route as AppMyAttendanceRouteImport } from './routes/_app.my-attendance'
import { Route as AppLeaveRouteImport } from './routes/_app.leave'
import { Route as AppIntegrationMonitoringRouteImport } from './routes/_app.integration-monitoring'
import { Route as AppIntegrationConfigurationsRouteImport } from './routes/_app.integration-configurations'
import { Route as AppHolidaysRouteImport } from './routes/_app.holidays'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDirectoryRouteImport } from './routes/_app.directory'
import { Route as AppDataExchangeRouteImport } from './routes/_app.data-exchange'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientGoliveRouteImport } from './routes/_app.client-golive'
import { Route as AppClientApprovalsRouteImport } from './routes/_app.client-approvals'
import { Route as AppAuditHistoryRouteImport } from './routes/_app.audit-history'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppRecruitmentCandidatesIdRouteImport } from './routes/_app.recruitment-candidates.$id'
import { Route as AppEmployeesIdRouteImport } from './routes/_app.employees.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemOrganizationRoute =
  DesignSystemOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DesignSystemRoute,
  } as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantManagementRoute = AppTenantManagementRouteImport.update({
  id: '/tenant-management',
  path: '/tenant-management',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentRequisitionsRoute =
  AppRecruitmentRequisitionsRouteImport.update({
    id: '/recruitment-requisitions',
    path: '/recruitment-requisitions',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecruitmentPreboardingRoute =
  AppRecruitmentPreboardingRouteImport.update({
    id: '/recruitment-preboarding',
    path: '/recruitment-preboarding',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecruitmentPositionsRoute = AppRecruitmentPositionsRouteImport.update({
  id: '/recruitment-positions',
  path: '/recruitment-positions',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentPipelineRoute = AppRecruitmentPipelineRouteImport.update({
  id: '/recruitment-pipeline',
  path: '/recruitment-pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentOffersRoute = AppRecruitmentOffersRouteImport.update({
  id: '/recruitment-offers',
  path: '/recruitment-offers',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentInterviewsRoute =
  AppRecruitmentInterviewsRouteImport.update({
    id: '/recruitment-interviews',
    path: '/recruitment-interviews',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecruitmentCandidatesRoute =
  AppRecruitmentCandidatesRouteImport.update({
    id: '/recruitment-candidates',
    path: '/recruitment-candidates',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecruitmentRoute = AppRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderDashboardRoute = AppProviderDashboardRouteImport.update({
  id: '/provider-dashboard',
  path: '/provider-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPayslipsRoute = AppPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => AppRoute,
} as any)
const AppOutsourcingRoute = AppOutsourcingRouteImport.update({
  id: '/outsourcing',
  path: '/outsourcing',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsDashboardRoute = AppOperationsDashboardRouteImport.update({
  id: '/operations-dashboard',
  path: '/operations-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTeamRoute = AppMyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => AppRoute,
} as any)
const AppMyPayslipsRoute = AppMyPayslipsRouteImport.update({
  id: '/my-payslips',
  path: '/my-payslips',
  getParentRoute: () => AppRoute,
} as any)
const AppMyLeaveRoute = AppMyLeaveRouteImport.update({
  id: '/my-leave',
  path: '/my-leave',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAttendanceRoute = AppMyAttendanceRouteImport.update({
  id: '/my-attendance',
  path: '/my-attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationMonitoringRoute =
  AppIntegrationMonitoringRouteImport.update({
    id: '/integration-monitoring',
    path: '/integration-monitoring',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationConfigurationsRoute =
  AppIntegrationConfigurationsRouteImport.update({
    id: '/integration-configurations',
    path: '/integration-configurations',
    getParentRoute: () => AppRoute,
  } as any)
const AppHolidaysRoute = AppHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryRoute = AppDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppDataExchangeRoute = AppDataExchangeRouteImport.update({
  id: '/data-exchange',
  path: '/data-exchange',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientGoliveRoute = AppClientGoliveRouteImport.update({
  id: '/client-golive',
  path: '/client-golive',
  getParentRoute: () => AppRoute,
} as any)
const AppClientApprovalsRoute = AppClientApprovalsRouteImport.update({
  id: '/client-approvals',
  path: '/client-approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditHistoryRoute = AppAuditHistoryRouteImport.update({
  id: '/audit-history',
  path: '/audit-history',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentCandidatesIdRoute =
  AppRecruitmentCandidatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppRecruitmentCandidatesRoute,
  } as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-history': typeof AppAuditHistoryRoute
  '/client-approvals': typeof AppClientApprovalsRoute
  '/client-golive': typeof AppClientGoliveRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-exchange': typeof AppDataExchangeRoute
  '/directory': typeof AppDirectoryRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/help': typeof AppHelpRoute
  '/holidays': typeof AppHolidaysRoute
  '/integration-configurations': typeof AppIntegrationConfigurationsRoute
  '/integration-monitoring': typeof AppIntegrationMonitoringRoute
  '/leave': typeof AppLeaveRoute
  '/my-attendance': typeof AppMyAttendanceRoute
  '/my-leave': typeof AppMyLeaveRoute
  '/my-payslips': typeof AppMyPayslipsRoute
  '/my-team': typeof AppMyTeamRoute
  '/notifications': typeof AppNotificationsRoute
  '/operations-dashboard': typeof AppOperationsDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/outsourcing': typeof AppOutsourcingRoute
  '/payslips': typeof AppPayslipsRoute
  '/profile': typeof AppProfileRoute
  '/provider-dashboard': typeof AppProviderDashboardRoute
  '/recruitment': typeof AppRecruitmentRoute
  '/recruitment-candidates': typeof AppRecruitmentCandidatesRouteWithChildren
  '/recruitment-interviews': typeof AppRecruitmentInterviewsRoute
  '/recruitment-offers': typeof AppRecruitmentOffersRoute
  '/recruitment-pipeline': typeof AppRecruitmentPipelineRoute
  '/recruitment-positions': typeof AppRecruitmentPositionsRoute
  '/recruitment-preboarding': typeof AppRecruitmentPreboardingRoute
  '/recruitment-requisitions': typeof AppRecruitmentRequisitionsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/tenant-management': typeof AppTenantManagementRoute
  '/users': typeof AppUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/design-system/organization': typeof DesignSystemOrganizationRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/recruitment-candidates/$id': typeof AppRecruitmentCandidatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-history': typeof AppAuditHistoryRoute
  '/client-approvals': typeof AppClientApprovalsRoute
  '/client-golive': typeof AppClientGoliveRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-exchange': typeof AppDataExchangeRoute
  '/directory': typeof AppDirectoryRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/help': typeof AppHelpRoute
  '/holidays': typeof AppHolidaysRoute
  '/integration-configurations': typeof AppIntegrationConfigurationsRoute
  '/integration-monitoring': typeof AppIntegrationMonitoringRoute
  '/leave': typeof AppLeaveRoute
  '/my-attendance': typeof AppMyAttendanceRoute
  '/my-leave': typeof AppMyLeaveRoute
  '/my-payslips': typeof AppMyPayslipsRoute
  '/my-team': typeof AppMyTeamRoute
  '/notifications': typeof AppNotificationsRoute
  '/operations-dashboard': typeof AppOperationsDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/outsourcing': typeof AppOutsourcingRoute
  '/payslips': typeof AppPayslipsRoute
  '/profile': typeof AppProfileRoute
  '/provider-dashboard': typeof AppProviderDashboardRoute
  '/recruitment': typeof AppRecruitmentRoute
  '/recruitment-candidates': typeof AppRecruitmentCandidatesRouteWithChildren
  '/recruitment-interviews': typeof AppRecruitmentInterviewsRoute
  '/recruitment-offers': typeof AppRecruitmentOffersRoute
  '/recruitment-pipeline': typeof AppRecruitmentPipelineRoute
  '/recruitment-positions': typeof AppRecruitmentPositionsRoute
  '/recruitment-preboarding': typeof AppRecruitmentPreboardingRoute
  '/recruitment-requisitions': typeof AppRecruitmentRequisitionsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/tenant-management': typeof AppTenantManagementRoute
  '/users': typeof AppUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/design-system/organization': typeof DesignSystemOrganizationRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/recruitment-candidates/$id': typeof AppRecruitmentCandidatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit-history': typeof AppAuditHistoryRoute
  '/_app/client-approvals': typeof AppClientApprovalsRoute
  '/_app/client-golive': typeof AppClientGoliveRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/data-exchange': typeof AppDataExchangeRoute
  '/_app/directory': typeof AppDirectoryRoute
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/help': typeof AppHelpRoute
  '/_app/holidays': typeof AppHolidaysRoute
  '/_app/integration-configurations': typeof AppIntegrationConfigurationsRoute
  '/_app/integration-monitoring': typeof AppIntegrationMonitoringRoute
  '/_app/leave': typeof AppLeaveRoute
  '/_app/my-attendance': typeof AppMyAttendanceRoute
  '/_app/my-leave': typeof AppMyLeaveRoute
  '/_app/my-payslips': typeof AppMyPayslipsRoute
  '/_app/my-team': typeof AppMyTeamRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/operations-dashboard': typeof AppOperationsDashboardRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/outsourcing': typeof AppOutsourcingRoute
  '/_app/payslips': typeof AppPayslipsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/provider-dashboard': typeof AppProviderDashboardRoute
  '/_app/recruitment': typeof AppRecruitmentRoute
  '/_app/recruitment-candidates': typeof AppRecruitmentCandidatesRouteWithChildren
  '/_app/recruitment-interviews': typeof AppRecruitmentInterviewsRoute
  '/_app/recruitment-offers': typeof AppRecruitmentOffersRoute
  '/_app/recruitment-pipeline': typeof AppRecruitmentPipelineRoute
  '/_app/recruitment-positions': typeof AppRecruitmentPositionsRoute
  '/_app/recruitment-preboarding': typeof AppRecruitmentPreboardingRoute
  '/_app/recruitment-requisitions': typeof AppRecruitmentRequisitionsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tenant-management': typeof AppTenantManagementRoute
  '/_app/users': typeof AppUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/design-system/organization': typeof DesignSystemOrganizationRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/recruitment-candidates/$id': typeof AppRecruitmentCandidatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/login'
    | '/about'
    | '/announcements'
    | '/attendance'
    | '/audit-history'
    | '/client-approvals'
    | '/client-golive'
    | '/dashboard'
    | '/data-exchange'
    | '/directory'
    | '/employees'
    | '/help'
    | '/holidays'
    | '/integration-configurations'
    | '/integration-monitoring'
    | '/leave'
    | '/my-attendance'
    | '/my-leave'
    | '/my-payslips'
    | '/my-team'
    | '/notifications'
    | '/operations-dashboard'
    | '/organization'
    | '/outsourcing'
    | '/payslips'
    | '/profile'
    | '/provider-dashboard'
    | '/recruitment'
    | '/recruitment-candidates'
    | '/recruitment-interviews'
    | '/recruitment-offers'
    | '/recruitment-pipeline'
    | '/recruitment-positions'
    | '/recruitment-preboarding'
    | '/recruitment-requisitions'
    | '/roles'
    | '/settings'
    | '/tenant-management'
    | '/users'
    | '/api/$'
    | '/design-system/organization'
    | '/employees/$id'
    | '/recruitment-candidates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/login'
    | '/about'
    | '/announcements'
    | '/attendance'
    | '/audit-history'
    | '/client-approvals'
    | '/client-golive'
    | '/dashboard'
    | '/data-exchange'
    | '/directory'
    | '/employees'
    | '/help'
    | '/holidays'
    | '/integration-configurations'
    | '/integration-monitoring'
    | '/leave'
    | '/my-attendance'
    | '/my-leave'
    | '/my-payslips'
    | '/my-team'
    | '/notifications'
    | '/operations-dashboard'
    | '/organization'
    | '/outsourcing'
    | '/payslips'
    | '/profile'
    | '/provider-dashboard'
    | '/recruitment'
    | '/recruitment-candidates'
    | '/recruitment-interviews'
    | '/recruitment-offers'
    | '/recruitment-pipeline'
    | '/recruitment-positions'
    | '/recruitment-preboarding'
    | '/recruitment-requisitions'
    | '/roles'
    | '/settings'
    | '/tenant-management'
    | '/users'
    | '/api/$'
    | '/design-system/organization'
    | '/employees/$id'
    | '/recruitment-candidates/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/design-system'
    | '/login'
    | '/_app/about'
    | '/_app/announcements'
    | '/_app/attendance'
    | '/_app/audit-history'
    | '/_app/client-approvals'
    | '/_app/client-golive'
    | '/_app/dashboard'
    | '/_app/data-exchange'
    | '/_app/directory'
    | '/_app/employees'
    | '/_app/help'
    | '/_app/holidays'
    | '/_app/integration-configurations'
    | '/_app/integration-monitoring'
    | '/_app/leave'
    | '/_app/my-attendance'
    | '/_app/my-leave'
    | '/_app/my-payslips'
    | '/_app/my-team'
    | '/_app/notifications'
    | '/_app/operations-dashboard'
    | '/_app/organization'
    | '/_app/outsourcing'
    | '/_app/payslips'
    | '/_app/profile'
    | '/_app/provider-dashboard'
    | '/_app/recruitment'
    | '/_app/recruitment-candidates'
    | '/_app/recruitment-interviews'
    | '/_app/recruitment-offers'
    | '/_app/recruitment-pipeline'
    | '/_app/recruitment-positions'
    | '/_app/recruitment-preboarding'
    | '/_app/recruitment-requisitions'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/tenant-management'
    | '/_app/users'
    | '/api/$'
    | '/design-system/organization'
    | '/_app/employees/$id'
    | '/_app/recruitment-candidates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/organization': {
      id: '/design-system/organization'
      path: '/organization'
      fullPath: '/design-system/organization'
      preLoaderRoute: typeof DesignSystemOrganizationRouteImport
      parentRoute: typeof DesignSystemRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenant-management': {
      id: '/_app/tenant-management'
      path: '/tenant-management'
      fullPath: '/tenant-management'
      preLoaderRoute: typeof AppTenantManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment-requisitions': {
      id: '/_app/recruitment-requisitions'
      path: '/recruitment-requisitions'
      fullPath: '/recruitment-requisitions'
      preLoaderRoute: typeof AppRecruitmentRequisitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment-preboarding': {
      id: '/_app/recruitment-preboarding'
      path: '/recruitment-preboarding'
      fullPath: '/recruitment-preboarding'
      preLoaderRoute: typeof AppRecruitmentPreboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment-positions': {
      id: '/_app/recruitment-positions'
      path: '/recruitment-positions'
      fullPath: '/recruitment-positions'
      preLoaderRoute: typeof AppRecruitmentPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment-pipeline': {
      id: '/_app/recruitment-pipeline'
      path: '/recruitment-pipeline'
      fullPath: '/recruitment-pipeline'
      preLoaderRoute: typeof AppRecruitmentPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment-offers': {
      id: '/_app/recruitment-offers'
      path: '/recruitment-offers'
      fullPath: '/recruitment-offers'
      preLoaderRoute: typeof AppRecruitmentOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment-interviews': {
      id: '/_app/recruitment-interviews'
      path: '/recruitment-interviews'
      fullPath: '/recruitment-interviews'
      preLoaderRoute: typeof AppRecruitmentInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment-candidates': {
      id: '/_app/recruitment-candidates'
      path: '/recruitment-candidates'
      fullPath: '/recruitment-candidates'
      preLoaderRoute: typeof AppRecruitmentCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment': {
      id: '/_app/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AppRecruitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provider-dashboard': {
      id: '/_app/provider-dashboard'
      path: '/provider-dashboard'
      fullPath: '/provider-dashboard'
      preLoaderRoute: typeof AppProviderDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payslips': {
      id: '/_app/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof AppPayslipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outsourcing': {
      id: '/_app/outsourcing'
      path: '/outsourcing'
      fullPath: '/outsourcing'
      preLoaderRoute: typeof AppOutsourcingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations-dashboard': {
      id: '/_app/operations-dashboard'
      path: '/operations-dashboard'
      fullPath: '/operations-dashboard'
      preLoaderRoute: typeof AppOperationsDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-team': {
      id: '/_app/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof AppMyTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-payslips': {
      id: '/_app/my-payslips'
      path: '/my-payslips'
      fullPath: '/my-payslips'
      preLoaderRoute: typeof AppMyPayslipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-leave': {
      id: '/_app/my-leave'
      path: '/my-leave'
      fullPath: '/my-leave'
      preLoaderRoute: typeof AppMyLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-attendance': {
      id: '/_app/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof AppMyAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave': {
      id: '/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integration-monitoring': {
      id: '/_app/integration-monitoring'
      path: '/integration-monitoring'
      fullPath: '/integration-monitoring'
      preLoaderRoute: typeof AppIntegrationMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integration-configurations': {
      id: '/_app/integration-configurations'
      path: '/integration-configurations'
      fullPath: '/integration-configurations'
      preLoaderRoute: typeof AppIntegrationConfigurationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holidays': {
      id: '/_app/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AppHolidaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directory': {
      id: '/_app/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AppDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-exchange': {
      id: '/_app/data-exchange'
      path: '/data-exchange'
      fullPath: '/data-exchange'
      preLoaderRoute: typeof AppDataExchangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client-golive': {
      id: '/_app/client-golive'
      path: '/client-golive'
      fullPath: '/client-golive'
      preLoaderRoute: typeof AppClientGoliveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client-approvals': {
      id: '/_app/client-approvals'
      path: '/client-approvals'
      fullPath: '/client-approvals'
      preLoaderRoute: typeof AppClientApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-history': {
      id: '/_app/audit-history'
      path: '/audit-history'
      fullPath: '/audit-history'
      preLoaderRoute: typeof AppAuditHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment-candidates/$id': {
      id: '/_app/recruitment-candidates/$id'
      path: '/$id'
      fullPath: '/recruitment-candidates/$id'
      preLoaderRoute: typeof AppRecruitmentCandidatesIdRouteImport
      parentRoute: typeof AppRecruitmentCandidatesRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
  }
}

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppRecruitmentCandidatesRouteChildren {
  AppRecruitmentCandidatesIdRoute: typeof AppRecruitmentCandidatesIdRoute
}

const AppRecruitmentCandidatesRouteChildren: AppRecruitmentCandidatesRouteChildren =
  {
    AppRecruitmentCandidatesIdRoute: AppRecruitmentCandidatesIdRoute,
  }

const AppRecruitmentCandidatesRouteWithChildren =
  AppRecruitmentCandidatesRoute._addFileChildren(
    AppRecruitmentCandidatesRouteChildren,
  )

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditHistoryRoute: typeof AppAuditHistoryRoute
  AppClientApprovalsRoute: typeof AppClientApprovalsRoute
  AppClientGoliveRoute: typeof AppClientGoliveRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataExchangeRoute: typeof AppDataExchangeRoute
  AppDirectoryRoute: typeof AppDirectoryRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppHelpRoute: typeof AppHelpRoute
  AppHolidaysRoute: typeof AppHolidaysRoute
  AppIntegrationConfigurationsRoute: typeof AppIntegrationConfigurationsRoute
  AppIntegrationMonitoringRoute: typeof AppIntegrationMonitoringRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppMyAttendanceRoute: typeof AppMyAttendanceRoute
  AppMyLeaveRoute: typeof AppMyLeaveRoute
  AppMyPayslipsRoute: typeof AppMyPayslipsRoute
  AppMyTeamRoute: typeof AppMyTeamRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOperationsDashboardRoute: typeof AppOperationsDashboardRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppOutsourcingRoute: typeof AppOutsourcingRoute
  AppPayslipsRoute: typeof AppPayslipsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProviderDashboardRoute: typeof AppProviderDashboardRoute
  AppRecruitmentRoute: typeof AppRecruitmentRoute
  AppRecruitmentCandidatesRoute: typeof AppRecruitmentCandidatesRouteWithChildren
  AppRecruitmentInterviewsRoute: typeof AppRecruitmentInterviewsRoute
  AppRecruitmentOffersRoute: typeof AppRecruitmentOffersRoute
  AppRecruitmentPipelineRoute: typeof AppRecruitmentPipelineRoute
  AppRecruitmentPositionsRoute: typeof AppRecruitmentPositionsRoute
  AppRecruitmentPreboardingRoute: typeof AppRecruitmentPreboardingRoute
  AppRecruitmentRequisitionsRoute: typeof AppRecruitmentRequisitionsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTenantManagementRoute: typeof AppTenantManagementRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditHistoryRoute: AppAuditHistoryRoute,
  AppClientApprovalsRoute: AppClientApprovalsRoute,
  AppClientGoliveRoute: AppClientGoliveRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDataExchangeRoute: AppDataExchangeRoute,
  AppDirectoryRoute: AppDirectoryRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppHelpRoute: AppHelpRoute,
  AppHolidaysRoute: AppHolidaysRoute,
  AppIntegrationConfigurationsRoute: AppIntegrationConfigurationsRoute,
  AppIntegrationMonitoringRoute: AppIntegrationMonitoringRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppMyAttendanceRoute: AppMyAttendanceRoute,
  AppMyLeaveRoute: AppMyLeaveRoute,
  AppMyPayslipsRoute: AppMyPayslipsRoute,
  AppMyTeamRoute: AppMyTeamRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOperationsDashboardRoute: AppOperationsDashboardRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppOutsourcingRoute: AppOutsourcingRoute,
  AppPayslipsRoute: AppPayslipsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProviderDashboardRoute: AppProviderDashboardRoute,
  AppRecruitmentRoute: AppRecruitmentRoute,
  AppRecruitmentCandidatesRoute: AppRecruitmentCandidatesRouteWithChildren,
  AppRecruitmentInterviewsRoute: AppRecruitmentInterviewsRoute,
  AppRecruitmentOffersRoute: AppRecruitmentOffersRoute,
  AppRecruitmentPipelineRoute: AppRecruitmentPipelineRoute,
  AppRecruitmentPositionsRoute: AppRecruitmentPositionsRoute,
  AppRecruitmentPreboardingRoute: AppRecruitmentPreboardingRoute,
  AppRecruitmentRequisitionsRoute: AppRecruitmentRequisitionsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTenantManagementRoute: AppTenantManagementRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DesignSystemRouteChildren {
  DesignSystemOrganizationRoute: typeof DesignSystemOrganizationRoute
}

const DesignSystemRouteChildren: DesignSystemRouteChildren = {
  DesignSystemOrganizationRoute: DesignSystemOrganizationRoute,
}

const DesignSystemRouteWithChildren = DesignSystemRoute._addFileChildren(
  DesignSystemRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DesignSystemRoute: DesignSystemRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
